remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme

title: ZUPAH BV | Tom Claus
description: We combineren diepgaande energy expertise met sterke IT-kennis om bedrijven te helpen technologie- en energie-uitdagingen om te zetten in duurzame groei.

show_downloads: false


# https://github.com/jekyll/minima
