title: ZUPAH BV | Tom Claus
description: > 
  We combineren diepgaande energy expertise met sterke IT-kennis om 
  bedrijven te helpen technologie- en energie-uitdagingen om te zetten 
  in duurzame groei.

author:
   name: Tom Claus
   email: mail@tomclaus.be

url: 'https://tmcls.github.io/'   # your main domain
baseurl: 'tomclaus.be/'           # if you're using custom domain keep this blank example: baseurl: ''

remote_theme: "jekyll/minima"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata

# https://github.com/jekyll/minima
minima:
  skin: classic

  nav_pages:
    - about.md
    - zupah-be.md

  show_excerpts: true