title: ZUPAH BV | Tom Claus
description: > 
  We combineren diepgaande energy expertise met sterke IT-kennis om 
  bedrijven te helpen technologie- en energie-uitdagingen om te zetten 
  in duurzame groei.

author:
   name: Tom Claus
   email: mail@tomclaus.be

remote_theme: "jekyll/minima"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic


# https://github.com/jekyll/minima
